services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "9000:80"
    # networks:
    #   - internal
    volumes:
      - ./data:/var/www/html/php_basis

# networks:
#   internal:
#     driver: bridge

